[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
which = "6"
sha2 = "0.10"
hex = "0.4"
serde_json = "1"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
shell-escape = "0.1"
