name = "pager"
subsystem = 4000

[[routines]]
name = "page_request"
id = 4000
[[routines.inputs]]
name = "object_id"
type = "u64"
[[routines.inputs]]
name = "offset"
type = "u64"
[[routines.inputs]]
name = "size"
type = "u32"
[[routines.inputs]]
name = "protection"
type = "u32"
[[routines.outputs]]
name = "phys_addr"
type = "u64"

