version: '3.8'

services:
  mach_r_builder:
    build: .
    volumes:
      - .:/workspace
      - cargo_cache:/usr/local/cargo/registry
    environment:
      - RUSTFLAGS=-A warnings
    working_dir: /workspace

volumes:
  cargo_cache:
